parserOptions:
  ecmaVersion: 2017
  sourceType: 'module'

env:
  es6: true
  node: true
  commonjs: true
  browser: false
  mocha: true

rules:
  max-nested-callbacks: [2, 5]

extends: 'htmlacademy/node'
